- lang/cpp/reef-bridge-clr/pom.xml
- lang/cs/Org.Apache.REEF.Evaluator/NugetExeFix.txt
- pom.xml
Update excludes with the new folder structures
IIRA: Reef-138. (https://issues.apache.org/jira/browse/REEF-138)
Author Julia wang
email: jwang98052@yahoo.com
> [REEF-138] Excludes for Apache-RAT for the new .NET project structure

- lang/cs/Org.Apache.REEF.All/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Bridge/AssemblyInfo.cpp
- lang/cs/Org.Apache.REEF.Client/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Common.Tests/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Common/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Driver/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Evaluator/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Examples.HelloREEF/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Examples/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Network.Examples.Client/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Network.Examples/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Network.Tests/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Network/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Tang.Examples/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Tang.Tests/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Tang.Tools/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Tang/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Tests/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Utilities/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Wake.Tests/Properties/AssemblyInfo.cs
- lang/cs/Org.Apache.REEF.Wake/Properties/AssemblyInfo.cs
This change replaces all the assembly versions with `0.11.0.0` to sync them with the project version.
JIRA: [REEF-280](https://issues.apache.org/jira/browse/REEF-280)
> [REEF-280] Update assembly versions to 0.11.0.0

- lang/java/reef-applications/reef-vortex/src/main/java/org/apache/reef/vortex/driver/Tasklet.java
This PR makes VortexFuture class serializable and
consequently resolves a high-priority findbug warning on Tasklet class.
JIRA:
[REEF-774](https://issues.apache.org/jira/browse/REEF-774)
Pull Request:
This closes #512
> [REEF-774] Remove Serializable interface from Tasklet

- lang/java/reef-webserver/src/main/java/org/apache/reef/webserver/HttpServerReefEventHandler.java
This PR addresses the followings issues in HttpServerReefEventHandler:
* Fix NullPointerException on `filename` query without arguments
* Use typed list to avoid dynamic type-casting
* Remove mixed use of both `getWriter()` and `getOutputStream()'
JIRA:
[REEF-781](https://issues.apache.org/jira/browse/REEF-781)
Pull Request:
Closes #520
> [REEF-781] Fix NPE on receiving filename query without arguments

- lang/java/reef-wake/wake/src/main/java/org/apache/reef/wake/WakeParameters.java
- lang/java/reef-wake/wake/src/main/java/org/apache/reef/wake/remote/RemoteConfiguration.java
JIRA: [REEF-1753](https://issues.apache.org/jira/browse/REEF-1753)
This PR prevents RemoteStage from being closed while a thread is retrying to construct a connection. I fixed the code by making `REMOTE_EXECUTOR_SHUTDOWN_TIMEOUT` greater than `REMOTE_CONNECTION_NUMBER_OF_RETRIES` * `REMOTE_CONNECTION_RETRY_TIMEOUT`
Closes #
> [REEF-1753] Intermittent failures of CloseEvaluatorTest in local runtime

- lang/cs/Org.Apache.REEF.Driver/Evaluator/EvaluatorRequest.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureBlockBlobFileSystem.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureDataLakeFileSystem.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestHadoopFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureBlockBlobFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/AzureDataLakeFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/Hadoop/HadoopFileSystem.cs
…prefix is given path already contains it
> [REEF-2016] - Fix CreateUriForPath methods of different IFileSystems to not append prefix if given path already contains it

- lang/cs/Org.Apache.REEF.Client/Avro/AzureBatch/AvroAzureBatchJobSubmissionParameters.cs
- lang/cs/Org.Apache.REEF.Client/AzureBatch/Util/JobJarMaker.cs
- lang/java/reef-bridge-client/src/main/avro/JobSubmissionParameters.avsc
- lang/java/reef-bridge-client/src/main/java/org/apache/reef/bridge/client/AzureBatchBootstrapDriverConfigGenerator.java
- lang/java/reef-bridge-client/src/main/java/org/apache/reef/bridge/client/AzureBatchBootstrapREEFLauncher.java
When running REEF .NET on Azure Batch, Azure Batch key and Azure Storage
account key are exposed in job-submission-params.json file. Those keys
are unnecessary, as environment variables "AZ_BATCH_AUTHENTICATION_TOKEN"
is set for Azure Batch token, and "AZURE_STORAGE_CONTAINER_SAS_TOKEN_ENV" is set for Azure Storage Account token, when submitting Azure Batch Job.
JIRA:
[REEF-2031](https://issues.apache.org/jira/browse/REEF-2031)
Pull request:
This closes #1469
> [REEF-2031]Azure Batch credentials exposed in job-submission-params.json in REEF.NET

- lang/cs/Org.Apache.REEF.IO.Tests/TestLocalFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/Local/LocalFileSystem.cs
[REEF-2037] Introduce configurable azure blob exponential retry policy
DeleteDirectory of LocalFileSystem does not do recursive delete unlike other filesystem implementations
JIRA:
[REEF-2037](https://issues.apache.org/jira/browse/REEF-2037)
Pull request:
This closes [1474](https://github.com/apache/reef/pull/1474)
> [REEF-2037] Make local file system deleteDirectory api recursive

- lang/cs/Org.Apache.REEF.Driver/Evaluator/EvaluatorRequest.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureBlockBlobFileSystemE2E.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureBlockBlobFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlobClient.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/ICloudBlobClient.cs
Fixed the GetChildren api and added unit test.
JIRA:
[REEF-2022] https://issues.apache.org/jira/browse/REEF-2022
> [REEF-2022] Fixed AzureBlockBlobFileSystem.GetChildren api and unit tests

- lang/java/reef-common/src/main/java/org/apache/reef/runtime/common/driver/evaluator/EvaluatorDescriptorBuilder.java
- lang/java/reef-common/src/main/java/org/apache/reef/runtime/common/driver/evaluator/EvaluatorDescriptorBuilderFactory.java
- lang/java/reef-common/src/main/java/org/apache/reef/runtime/common/driver/evaluator/EvaluatorDescriptorImpl.java
- lang/java/reef-common/src/main/java/org/apache/reef/runtime/common/driver/evaluator/EvaluatorManager.java
- lang/java/reef-common/src/main/java/org/apache/reef/runtime/common/driver/evaluator/EvaluatorManagerFactory.java
The new bridge needs access to create an EvaluatorDescriptor. This PR
creates a factor and builder for EvaluatorDescriptor that can be
injected via Tang. Default implementation creates an
EvaluatorDescriptImpl.
Pull Request:
Closes #
> [REEF-2024] Prepare existing artifacts for new bridge module.

- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureDataLakeFileSystem.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureDataLakeFileSystemE2E.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/AzureDataLakeFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/AzureDataLakeFileSystemConfiguration.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/AzureDataLakeFileSystemConfigurationProvider.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/AzureDataLakeStoreClient.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/IDataLakeStoreClient.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/Parameters/DataLakeStorageAccountFQDN.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureDataLake/Parameters/DataLakeStorageAccountFqdn.cs
This addressed the issue by renaming the parameter AdlsAccountName to
AdlsAccountFQDN for clarity.
JIRA:
[REEF-2034](https://issues.apache.org/jira/browse/REEF-2034)
Pull request:
This closes #
> [REEF-2034] AdlsAccountName Expects FQDN

- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureBlockBlobFileSystemE2E.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlobClient.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlobContainer.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlobDirectory.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlockBlob.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/RetryPolicy/Exponential/ExponentialRetryPolicy.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/RetryPolicy/Exponential/ExponentialRetryPolicyConfiguration.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/RetryPolicy/Exponential/ExponentialRetryPolicyParameterNames.cs
[REEF-2033] Introduce configurable azure blob exponential retry policy
Currently, the AzureBlob retry policy defaults to Azure Blob Client's default ExponentialRetryPolicy which has retry count as 3 and retry interval as 4 seconds. Higher load jobs require custom setting of these values to overcome azure blob throttling - https://issues.apache.org/jira/projects/REEF/issues/REEF-2017. This change allows user to set their own retry count and intervals for azure blob retry policy
JIRA:
[REEF-2033](https://issues.apache.org/jira/browse/REEF-2033)
Pull request:
This closes [1470](https://github.com/apache/reef/pull/1470)
> [REEF-2033] Introduce configurable azure blob exponential retry policy

- lang/cs/Org.Apache.REEF.Client/YARN/HDI/HDInsightClientConfiguration.cs
- lang/cs/Org.Apache.REEF.Examples.HelloREEF/HelloREEF.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureBlobFileSystem.cs
- lang/cs/Org.Apache.REEF.IO.Tests/TestAzureBlobFileSystemE2E.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureBlobFileSystem.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureBlobFileSystemConfiguration.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureBlobFileSystemConfigurationProvider.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/AzureCloudBlobClient.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/Parameters/AzureBlobStorageAccountKey.cs
- lang/cs/Org.Apache.REEF.IO/FileSystem/AzureBlob/Parameters/AzureBlobStorageAccountName.cs
Took out the connection string parameter and replaced with account name
and account key. Connection string is then constructed whenever
necessary.
[REEF-2035] (https://issues.apache.org/jira/browse/REEF-2035)
Pull Request:
This closes #
> [REEF-2035] BlobFs parameters should be account name and key

- pom.xml
This addressed the issue by:
* Upgrading the pom to use hadoop 2.9.1, where allocation ID is in the NMClient API.
JIRA:
[REEF-2047](https://issues.apache.org/jira/browse/REEF-2047)
Pull request:
This closes #
> [REEF-2047] Upgrade Hadoop Version Referenced by REEF to 2.9

- pom.xml
- website/src/site/resources/doap.rdf
Since we are using `GitBox`, we had better update the project information before making new release.
> [REEF-2055] Use `gitbox` instead of `git-wip-us`

- lang/java/reef-applications/reef-vortex/pom.xml
- pom.xml
Hi, in **apache-reef-0.16.0 (reef-reef-project-0.16.0\lang\java\reef-applications\reef-vortex module)**, there are mulptiple versions of **org.ow2.asm:asm.jar**. However, according to Maven's dependency management strategy, only **org.ow2.asm:asm:jar:4.2** can be loaded, and **org.ow2.asm:asm:jar:5.0.3** will be shadowed.
As shown in the following dependency tree, **com.esotericsoftware:kryo:jar:3.0.3:compile** expects to reference **org.ow2.asm:asm:jar:5.0.3:compile**. But due to dependency conflicts, Maven actually loads **org.ow2.asm:asm:jar:4.2**. As a result, **com.esotericsoftware:kryo:jar:3.0.3:compile** has to invoke the methods included in the unexpected version **org.ow2.asm:asm:jar:4.2**, which may cause inconsistent semantic behaviors.
For instance, method …
> [REEF-2056] Fix dependency conflict issue

- pom.xml
FindBugs plugin v 3.0.2 that we use does not work with newer versions of maven (3.6+).
We need to upgrade FindBugs to version 3.0.4.
JIRA: [REEF-2058](https://issues.apache.org/jira/projects/REEF/issues/REEF-2058)
> [REEF-2058] Update FindBugs to version 3.0.4

- .travis.yml
- lang/java/reef-bridge-proto-java/pom.xml
- lang/java/reef-runtime-azbatch/pom.xml
- lang/java/reef-runtime-hdinsight/pom.xml
- lang/java/reef-runtime-multi/pom.xml
- lang/java/reef-wake/wake/src/main/java/org/apache/reef/wake/remote/transport/netty/NettyMessagingTransport.java
- pom.xml
Summary of changes:
* upgrade avro, httpclient, and netty
* update gRPC and sync up netty versions for reef-bridge-proto-java and other modules
* fix the error in Wake to work with Netty 4.1 ([REEF-2059](https://issues.apache.org/jira/browse/REEF-2059))
Migration to newer Checkstyle and Findbugs will be separate PRs
JIRA:
[REEF-2057](https://issues.apache.org/jira/browse/REEF-2057)
> [REEF-2057] Update REEF dependencies

- lang/java/reef-common/src/main/resources/checkstyle-strict.xml
- lang/java/reef-common/src/main/resources/checkstyle-suppress.xml
- lang/java/reef-common/src/main/resources/checkstyle.xml
- pom.xml
Summary of changes:
* Update CheckStyle to version 8.29
* Update Maven CheckStyle plugin to version 3.1.0
* Update CheckStyle configuration files to match the newer version (remove outdated parameters, etc.)
JIRA: [REEF-2061](https://issues.apache.org/jira/projects/REEF/issues/REEF-2061)
> [REEF-2061] Upgrade checkstyle and related plugins to newer versions

- lang/java/reef-runtime-local/src/main/java/org/apache/reef/runtime/local/client/PreparedDriverFolderLauncher.java
- lang/java/reef-runtime-local/src/main/java/org/apache/reef/runtime/local/process/RunnableProcess.java
This PR includes changes:
- Catch and rethrow exceptions from spawning a driver process for a local job (local runtime).
- As a result, the client process can notice that the job has been failed to be submitted.
JIRA:
[REEF-2063](https://issues.apache.org/jira/projects/REEF/issues/REEF-2063)
> [REEF-2063] Propagate exceptions of driver process fail in local runtime

- dev/docker/ubuntu12.04-jdk7-hdp2.1.15/Dockerfile
- dev/docker/ubuntu12.04-jdk7-hdp2.2.7/Dockerfile
- dev/docker/ubuntu12.04-jdk7-hdp2.2.8/Dockerfile
- dev/docker/ubuntu12.04-jdk7-hdp2.3.2/Dockerfile
- dev/docker/ubuntu12.04-jdk7-hdp2.4/Dockerfile
- dev/docker/ubuntu12.04-jdk7-mesos0.24/Dockerfile
- dev/docker/ubuntu12.04-jdk7-mesos0.25/Dockerfile
- dev/docker/ubuntu12.04-jdk7-mesos0.26/Dockerfile
- dev/docker/ubuntu12.04-jdk7-mesos0.27/Dockerfile
- dev/docker/ubuntu12.04-jdk7-mesos0.28/Dockerfile
- dev/docker/ubuntu12.04-jdk7/Dockerfile
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
JIRA:
[REEF-2065](https://issues.apache.org/jira/browse/REEF-2065)
Pull Request:
Closes #1504 
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> [REEF-2065] optimization debian package manager tweaks

- .travis.yml
[Travis are now recommending removing the sudo tag.](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
> [TRIVIAL] Remove deprecated sudo setting

- lang/java/reef-runtime-local/src/main/java/org/apache/reef/runtime/local/client/PreparedDriverFolderLauncher.java
- lang/java/reef-runtime-local/src/main/java/org/apache/reef/runtime/local/process/RunnableProcess.java
Some unit tests depend on client-side `DriverLauncher` killing the Driver process by timeout. That behavior was broken in PR #1499, and we have to revert that change.
This commit is a roll back of PR #1499
JIRA: [REEF-2066](https://issues.apache.org/jira/projects/REEF/issues/REEF-2066)
> [REEF-2066] Bugfix: unit tests that depend on client-side timeout hung indefinitely

- dev/change_version.py
We no longer have the `build.DotNet.props` file in our system.
The script should update the file `lang/cs/build.Common.props` instead.
JIRA: [REEF-2068](https://issues.apache.org/jira/projects/REEF/issues/REEF-2068)
> [REEF-2068] Bugfix: change_version.py fails on file build.DotNet.props
